"""Generate the pseudo-experiment for a synthetic-recovery test.

The point of a synthetic recovery is that the answer is KNOWN.  We run the
platform once at a chosen D_s^true, keep the resulting voltage trace as if it
were measured data, and then ask the optimiser to find D_s back starting from
scrambled initial guesses.

If the chain cannot recover a parameter it was itself given, then no fitting
against real data can be trusted -- which is exactly why G5.0 comes before any
Chen2020 identification.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

import numpy as np

from identification.forward import (
    DS_KEY,
    Observation,
    ReplayCase,
    replay,
)


def generate(
    dataset_id: str,
    cell: str,
    rate: str,
    ds_true: float,
    output_root: Path,
    model_name: str = "SPM",
    parameter_set: Optional[str] = None,
) -> Observation:
    """Run one replay at ``ds_true`` and return its trace as the observation."""
    case = ReplayCase(
        dataset_id=dataset_id,
        cell=cell,
        rate=rate,
        model_name=model_name,
        parameter_set=parameter_set,
    ).resolve()

    src = {
        "logical_name": "particle_diffusivity",
        "source": "SYNTHETIC TRUTH -- not a measurement",
        "method": "identification/G5.0 synthetic observation",
        "unit": "m2/s",
    }
    t, v, res = replay(case, ds_true, source_record=src, output_root=output_root)

    applied = list(res.get("parameter_overrides_applied") or [])
    meta: Dict[str, Any] = {
        "truth_source": "SYNTHETIC -- generated by this platform, not measured",
        "truth_applied": applied,
        "note": (
            "This trace is the platform's own output at ds_true.  Recovering "
            "ds_true from it is a plumbing test, not a physics result."
        ),
    }
    obs = Observation(
        time_s=np.asarray(t, dtype=float),
        voltage_V=np.asarray(v, dtype=float),
        ds_true=float(ds_true),
        case=case,
        meta=meta,
    )
    obs.save(output_root / "observation" / "synthetic_observation.npz")
    return obs


def add_noise(
    obs: Observation,
    sigma_mV: float,
    seed: int,
    kind: str = "gaussian",
) -> Observation:
    """Return a copy of ``obs`` with measurement noise added.

    Why this is the next gate after plain synthetic recovery: a noiseless
    recovery is an inverse crime -- the same model, structure and parameter
    definition generate the data and invert it -- so it can only show the
    implementation is not broken.  Adding noise is the cheapest way to start
    asking the scientific question instead:

        is D_s still identifiable when the data are not exactly
        reproducible?

    Noise is added to the OBSERVATION only.  The forward model is untouched,
    so any deviation of the recovered value from the truth is attributable to
    the noise and to how strongly the observable constrains the parameter --
    not to a change in the model.
    """
    if kind != "gaussian":
        raise ValueError(f"unsupported noise kind {kind!r}")
    if sigma_mV < 0:
        raise ValueError("sigma_mV must be non-negative")

    rng = np.random.default_rng(int(seed))
    sigma_V = float(sigma_mV) / 1000.0
    noisy = np.asarray(obs.voltage_V, dtype=float) + rng.normal(
        0.0, sigma_V, size=np.asarray(obs.voltage_V).shape
    )

    meta = dict(obs.meta)
    meta["noise"] = {
        "kind": kind,
        "sigma_mV": float(sigma_mV),
        "sigma_V": sigma_V,
        "seed": int(seed),
        "note": ("noise added to the observation only; the forward model is "
                 "unchanged"),
    }
    return Observation(
        time_s=np.asarray(obs.time_s, dtype=float).copy(),
        voltage_V=noisy,
        ds_true=obs.ds_true,
        case=obs.case,
        meta=meta,
    )


def verify_truth_is_reproducible(
    obs: Observation, output_root: Path, rtol: float = 1e-9
) -> bool:
    """Re-running the truth must reproduce the observation bit-for-bit.

    Without this check a mismatch between the observation and the forward
    model could masquerade as identification error.
    """
    t, v, _ = replay(obs.case, obs.ds_true, output_root=output_root)
    if len(t) != len(obs.time_s):
        return False
    if not np.allclose(t, obs.time_s, rtol=0, atol=0):
        return False
    return bool(np.allclose(v, obs.voltage_V, rtol=rtol, atol=0))
